# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactHelloWorld' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactHelloWorld
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
    pod 'RNSha256', :path => '../node_modules/react-native-sha256'

  target 'reactHelloWorld-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactHelloWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end



end
